title: ShaominXie's Homepage
page-top-title: Shaomin Xie | è°¢å°‘æ•
site_description: Master's student

ğŸ“§email: "xieshaomin0805@163.com"
top-section-bg-text: Be what you wanna be
home-subtitle: Shaomin Xie&ensp;|&ensp;è°¢å°‘æ•
copyright-text: '&copy; Shaomin Xie 2023-2025. All Rights Reserved.'
